trigger: none  

pool:  
  vmImage: 'ubuntu-latest'  
  
variables:  
  - group: vg1 
  
stages:  
  - stage: DeployFlow   
    displayName: 'Stage 5 - Deploy Flow to Manged online endpoint'  
    dependsOn: []  
    jobs: 
      - job: ApproveDeployment  
        displayName: Approve for Online Endpoint Deployment of Flow 
        pool: server  
        steps:  
          - task: ManualValidation@0  
            inputs:  
              notifyUsers: |  
                youremail@example.com  
              instructions: "Approve the deployment for Batch Endpoint."  
              onTimeout: 'reject'  # Reject if approval not given in time   
      - job: DeployOnline   
        displayName: 'Deploy Online flow and Test Endpoint' 
        dependsOn: ApproveDeployment 
        steps:  
          - task: UsePythonVersion@0  
            inputs:  
              versionSpec: '3.10'  
              addToPath: true  
  
          - script: |  
              python -m pip install --upgrade pip  
              python -m pip install azure-identity  
              python -m pip install azure-ai-ml  
              python -m pip install python-dotenv 
              # azure dependencies
              python -m pip install azure-core
              python -m pip install azure-mgmt-authorization
              python -m pip install azure-mgmt-resource
              python -m pip install azure-mgmt-search
              python -m pip install azure-mgmt-cognitiveservices
            displayName: 'Install dependencies'  
  
          - task: DownloadPipelineArtifact@2  
            inputs:  
              buildType: 'specific'  
              project: 'SmartDocsPipeline'  
              definition: '34'  
              specificBuildWithTriggering: true  
              artifactName: 'environment'  
              targetPath: '$(Pipeline.Workspace)'  
  
          - task: DownloadPipelineArtifact@2  
            inputs: 
              buildType: 'specific'  
              project: 'SmartDocsPipeline'  
              definition: '37'  
              specificBuildWithTriggering: true    
              artifactName: 'DeployFlow'  
              targetPath: '$(Pipeline.Workspace)'  
  
          - task: AzureCLI@2  
            inputs:  
              azureSubscription: $(SERVICE_CONNECTION)  
              scriptType: bash  
              scriptLocation: inlineScript  
              inlineScript: |  
                echo "Logging into Azure..."  
                az account show  
                az extension add --upgrade --name ml -y  
                python ./Flow/generateyml.py 
                echo "Running deploy and test pipeline script..."  
                python ./Flow/deploy_test_flow.py 
            displayName: 'Authenticate and Run deploy and test pipeline script' 
  